GitHub Actions definition for automatic testing
anitvam/pps-bunny pull request #2
Opened 2021-08-18 16:13 UTC by anitvam

close #1

2021-08-19 09:52 UTC, aslucc approved these changes

2021-08-23 15:15 UTC, martaSpadoni approved these changes

2021-08-23 15:19 UTC, alessiarocco98 requested changes

2021-08-23 15:19 UTC, alessiarocco98 commented on .github/workflows/ci.yml
> +    branches: [master, develop]
Secondo voi sarebbe corretto successivamente aggiungere anche i nostri singoli branch, tipo mb, ar, al e ms?

2021-08-23 15:21 UTC, anitvam commented on .github/workflows/ci.yml
> +    branches: [master, develop]
Abbiamo un numero limitato di ore per poter eseguire le GitHub actions, mettere tutti questi controlli su ogni push mi sembra eccessivo, mentre per quanto riguarda le pull request queste saranno fatte solamente sui branch master e develop

2021-08-23 15:22 UTC, alessiarocco98 commented on .github/workflows/ci.yml
> +    branches: [master, develop]
Giustissimo! Chiaro, direi che a questo punto è la scelta migliore!

2021-08-23 15:22 UTC, alessiarocco98 approved these changes

2021-08-23 15:23 UTC, merged