Feature/ar gui disturbing factors
anitvam/pps-bunny pull request #57
Opened 2021-09-22 11:32 UTC by alessiarocco98

Close #53

2021-09-22 12:57 UTC, aslucc approved these changes

2021-09-22 15:36 UTC, anitvam requested changes
Manca l'implementazione della visualizzazione dei lupi e il cambiamento del background con quello selezionato

2021-09-24 07:34 UTC, aslucc reviewed
Io i lupi li vedo bene, ho notato delle cose minime 
- non hanno un movimento fluido, fanno uno spostamento e poi si bloccano, spostamento e poi si bloccano etc.
- quando ci sono tanti conigli sembra che ci "volino" sopra, forse sarebbe meglio in un piano visivo dietro ai conigli

2021-09-24 07:49 UTC, martaSpadoni commented on src/main/scala/view/View.scala
> +  def updateWolvesView(wolves: Population): Unit
perchè i wolves sono di tipo Population, che è una Seq[Bunny]?

2021-09-24 07:51 UTC, martaSpadoni commented on src/main/scala/view/scalaFX/FXControllers/BaseAppController.scala
> +  override def changeBackGroundEnvironment(factors: Factors, climate: Climate): Unit = {
```suggestion
  override def changeBackgroundEnvironment(factors: Factors, climate: Climate): Unit = {
```

2021-09-24 07:57 UTC, aslucc commented on src/main/scala/engine/SimulationConstants.scala
> +  object DisturbingFactors extends Enumeration {
Io farei una file separato per questa Enumeration

2021-09-24 07:58 UTC, aslucc commented on src/main/scala/model/genome/Kinds.scala
> +   * @param prettyName dominant specifies if it's dominant or not, it could be empty if not chosen yet
```suggestion
   * param prettyName the name of each allele, that will be shown to the user

2021-09-24 08:02 UTC, aslucc commented on src/main/scala/view/scalaFX/FXControllers/FactorsPanelController.scala
> +  private def factorOnClick(factor: CheckBox, disturbingFactor: Factor): Unit =
```suggestion
  private def onFactorClick(factor: CheckBox, disturbingFactor: Factor): Unit =
```

2021-09-24 08:04 UTC, aslucc commented on src/main/scala/view/scalaFX/FXControllers/FactorsPanelController.scala
> +}
Anche questi metterei tutti i nomi come onWolfClick, onToughFoodClick, etc. (mi sembra più corretto come inglese, però non so)

2021-09-24 08:08 UTC, aslucc commented on src/main/scala/view/scalaFX/components/WolfView.scala
> +
Essendo questa classe molto simile a BunnyView, forse si potrebbe fare una classe con tutti gli aspetti comuni delle due (ex. AnimalView? SimulationAnimalView? MovingAnimalView?)

2021-09-24 08:46 UTC, alessiarocco98 commented on src/main/scala/view/View.scala
> +  def updateWolvesView(wolves: Population): Unit
Perché ho fatto la proporzione del numero di lupi dalla lista dei Bunny ma effettivamente non ha nessun senso. Piuttosto passo direttamente il numero di coniglietti nella generazione corrente e poi uso l’informazione per generare il numero di lupi giusto.

2021-09-24 08:48 UTC, alessiarocco98 commented on src/main/scala/view/scalaFX/FXControllers/FactorsPanelController.scala
> +}
Ho utilizzato i nomi che usavano nelle guide scalafx per associare i metodi ma va benissimo anche così se ci piace di più

2021-09-24 09:52 UTC, aslucc commented on src/main/scala/view/scalaFX/FXControllers/FactorsPanelController.scala
> +}
Ah non pensavo fosse uno standard! Allora come vuoi

2021-09-25 08:53 UTC, anitvam commented on src/main/scala/engine/Simulation.scala
> +      updateWolvesView(getActualPopulation.length / 10 + 1)
perchè ti sei fatta questa implementazione? per fare dei test?

2021-09-25 08:58 UTC, anitvam commented on src/main/scala/view/View.scala
> +  def updateWolvesView(numberOfWolves: Int): Unit
siccome questo metodo ha una semantica leggermente diversa da `updateView` lo chiamerei `showWolves`

2021-09-25 09:05 UTC, anitvam commented on src/main/scala/engine/SimulationHistory.scala
>    /** Reset all the mutations added */
Questi metodi li hai implementati seguendo la tua versione di testing (suppongo) del model, ma non si interfacciano per niente con il mio model. A parte questa nota, qui stai violando MVC perchè stai facendo fare delle operazioni sulla gui di visualizzazione del cibo quando in realtà non si ha consapevolezza di quello che sta succedendo dentro all'implementazione grafica.

Diverso è il discorso per la visualizzazione dei lupi e l'aggiornamento dei conigli, perchè questi due sono eventi scatenati direttamente dal model

2021-09-25 09:06 UTC, anitvam commented on src/main/scala/view/View.scala
> +  def updateFoodView(foodFactors: Factors, climate: Climate): Unit
questo metodo non serve qui, bisogna metterlo in BaseAppController.

2021-09-25 09:16 UTC, anitvam commented on src/main/scala/view/scalaFX/FXControllers/BaseAppController.scala
> +
Questo non va qui, avevo creato apposta la classe `ViewImages` per separare tutti questi controlli sulle imagini mostrate a display. Inoltre non è possibile scriverlo in modo più funzionale, così è veramente poco leggibile...

2021-09-25 09:20 UTC, anitvam commented on src/main/scala/view/scalaFX/FXControllers/FactorsPanelController.scala
> +}
concordo con l'asia

2021-09-25 09:33 UTC, anitvam commented on src/main/scala/view/scalaFX/components/WolfView.scala
> +  var positionY: Double
questi sono da eliminare, l'ho rifattorizzato anche in `BunnyView`

2021-09-25 09:34 UTC, anitvam commented on src/main/scala/view/scalaFX/components/WolfView.scala
> +                                   var positionY: Double) extends DisturbingFactorView {
metti questi tre campi private

2021-09-25 09:36 UTC, anitvam commented on src/main/scala/view/scalaFX/components/WolfView.scala
> +trait DisturbingFactorView {
rinominalo in `WolfView`

2021-09-25 09:38 UTC, anitvam commented on src/main/scala/view/scalaFX/components/WolfView.scala
> +    }
Questa timeline è concettualmente sbagliata per il movimento dei lupi, perchè copiata troppo dalla logica del salto del coniglio.

Il salto del coniglio si suddivide in 3 parti: il cambiamento dell'immagine in quella che salta, la prima metà del salto e la seconda metà. Una volta svolto il movimento l'immagine viene rimessa quella del conglio fermo. A te tutta questa logica non serve perchè il lupo deve solo muoversi in orizzontale.

2021-09-25 09:44 UTC, anitvam commented on src/main/scala/view/scalaFX/components/WolfView.scala
> +    }
l'avanzamento a step è strettamente legato al movimento del coniglio, dovresti fare un ragionamento sulla `PREFERRED_BUNNY_PANEL_WIDTH` per mandare un lupo da un estremo all'altro dello schermo

2021-09-25 09:47 UTC, alessiarocco98 commented on src/main/scala/view/scalaFX/FXControllers/FactorsPanelController.scala
> +}
Cambio :)

2021-09-25 09:47 UTC, anitvam requested changes
* mancano le immagini piccoline di cibo scarso e temperature estreme 
* le immagini dei fattori (quelle piccoline) potrebbero essere centrate?
* bisogna gestire meglio il movimento dei lupi perchè copiato troppo da quello dei conigli
* se vengono scelti dei fattori prima di premere start viene lanciata una eccezione

2021-09-25 09:49 UTC, martaSpadoni requested changes
Oltre alle cose che ti sono state dette dalla Marti e dall'Asia, che condivido, io aggiungerei che i lupi vanno resi più grandi, al momento sono più piccoli dei conigli ed è un pò strano.

Se ridimensionando nuovamente le immagini che hai già modificato ti si dovessero sgranare troppo riprendile da develop. Inoltre, se ti può essere utile, ti dico già che i conigli sono grandi 60x64.

Infine cosa molto più importante, **se si scelgono i fattori da aggiungere prima di aver avviato la simulazione si genera un'eccezione**, questo non può accadere, deve essere gestita questa possibilità

2021-09-25 09:50 UTC, alessiarocco98 commented on src/main/scala/view/scalaFX/components/WolfView.scala
> +
Ci avevo pensato anche io ma per ora avevo accantonato l’idea solo perché un BunnyView appartiene al “mondo” mentre un WolfView dovrebbe appartenere a un’interfaccia di View dei fattori. 
ma posso provare e vedere cosa viene fuori.

2021-09-27 14:57 UTC, anitvam commented on src/main/scala/view/scalaFX/utilities/ViewImages.scala
> +  implicit def getBackgroundEnvironment(factors: Factors, climate: Climate): Background = {
un implicito ha un solo parametro... non ha senso dichiararlo implicito e poi chiamarlo come metodo....

2021-09-28 12:29 UTC, martaSpadoni commented on src/main/scala/view/scalaFX/utilities/ViewImages.scala
> +  }
```suggestion
  def getBackgroundEnvironment(factors: Factors, climate: Climate): Background = factors.sorted match {
    case List(DisturbingFactors.HIGH_FOOD, DisturbingFactors.LIMITED_FOOD, DisturbingFactors.TOUGH_FOOD)  =>
      getImageBackgroundCorrespondingToClimate(SummerImageRareHighToughFood(), WinterImageRareHighToughFood(), climate)
    case List(DisturbingFactors.HIGH_FOOD, DisturbingFactors.LIMITED_FOOD) =>
      getImageBackgroundCorrespondingToClimate(SummerImageRareHighFood(), WinterImageRareHighFood(), climate)
    case List(DisturbingFactors.HIGH_FOOD, DisturbingFactors.TOUGH_FOOD) =>
      getImageBackgroundCorrespondingToClimate(SummerImageHighToughFood(), WinterImageHighToughFood(), climate)
    case List(DisturbingFactors.LIMITED_FOOD, DisturbingFactors.TOUGH_FOOD)  =>
      getImageBackgroundCorrespondingToClimate(SummerImageRareToughFood(), WinterImageRareToughFood(), climate)
    case DisturbingFactors.HIGH_FOOD :: _ =>
      getImageBackgroundCorrespondingToClimate(SummerImageHighFood(), WinterImageHighFood(), climate)
    case DisturbingFactors.LIMITED_FOOD :: _ =>
      getImageBackgroundCorrespondingToClimate(SummerImageRareFood(), WinterImageRareFood(), climate)
    case DisturbingFactors.TOUGH_FOOD :: _ =>
      getImageBackgroundCorrespondingToClimate(SummerImageToughFood(), WinterImageToughFood(), climate)
    case _ => getImageBackgroundCorrespondingToClimate(SummerImage(), WinterImage(), climate)
```

ti propongo questo refactoring, trovo che i case sia non più funzionali, il sorted mi serve per evitare che il match non vada a buon fine a causa dell'ordine sbagliato degli elementi. Al momento il sorted funziona senza problemi perchè i DisturbingFactors sono stringhe temo però che se dovessimo cambiarli sarà necessario definire l'ordine per il nuovo tipo

2021-09-28 12:30 UTC, martaSpadoni commented on src/main/scala/view/scalaFX/utilities/ViewImages.scala
> +case class SummerImageToughFood(image: Image = EnvironmentImageUtils.SUMMER_IMAGE_TOUGH_FOOD) extends ClimateImage
noto solo ora un'incongruenza con i nomi: se chiamiamo il fattore LimitedFood non ha senso scrivere Rare nelle immagini io manterrei limited

2021-09-28 12:45 UTC, anitvam commented on src/main/scala/engine/Simulation.scala
> +      showWolves(getActualPopulation.length / 10 + 1)
MAGIC NUMBER. E poi non mi piace questa idea sul numero di lupi, io metterei un numero fisso di lupi che sono indipendenti dalla dimensione della popolazione, tipo 5/6.

2021-09-28 12:48 UTC, martaSpadoni commented on src/main/scala/view/scalaFX/components/WolfView.scala
> +      fitHeight = PREFERRED_WOLF_SIZE
Questo evita di farlo, perchè il resize di scalafx non è performante, ridimensiona le foto da un editor esterno. Quasi sicuramente è questo il motivo per il quale laggano quando sono tanti

2021-09-28 12:54 UTC, martaSpadoni commented on src/main/scala/view/scalaFX/utilities/ViewImages.scala
>    }
```suggestion
  implicit def actualClimate(background: ObjectProperty[JavaBackground]): Climate =
   if (background.value.getImages.get(0).getImage.getUrl.contains("cold")) Winter()
   else Summer()
```

2021-09-28 12:55 UTC, martaSpadoni commented on src/main/scala/view/scalaFX/utilities/ViewImages.scala
> +  val SUMMER_IMAGE_TOUGH_FOOD = new Image("/img/environment/hot_environment/hot_tough_food.png")
Capisco che prima queste val potessero essere utili ma dato che ora non si usano più suggerisco di eliminarle e di creare le immagini direttamente nelle relative case class definite sopra

2021-09-30 12:07 UTC, aslucc commented on src/main/scala/engine/SimulationHistory.scala
> +  def initialize(environment: Environment): Unit =
questo metodo non serve, era stato eliminato

2021-09-30 12:07 UTC, aslucc commented on src/main/scala/util/PimpScala.scala
> -  implicit class RichTuple2[A](tuple: (A, A)) {
Questa classe non va eliminata

2021-09-30 12:07 UTC, aslucc commented on src/main/scala/util/PimpScala.scala
> +  implicit class RichOption[A, B](option: Option[A]) {
Questa B va eliminata

2021-09-30 12:08 UTC, aslucc commented on src/main/scala/model/world/Reproduction.scala
> -      mutations filter { _.geneKind == gk } foreach { _ =>
Qui andava mantenuto questo refactoring

2021-09-30 12:09 UTC, aslucc commented on src/main/scala/model/world/Reproduction.scala
> -      val genesOfReproduction : List[Gene]=
Anche qui va mantenuta la versione rifattorizzata che hai eliminato

2021-09-30 12:10 UTC, aslucc commented on src/main/scala/engine/SimulationHistory.scala
> -  var history: History = List(Generation(Environment(Summer(), List.empty), generateInitialCouple.toSeq))
Quindi andava mantenuto il toSeq aggiunto in pimp scala, dato che generateInitialCouple  dovrebbe ritornare una Couple e non una Population nella versione refactored

2021-09-30 18:44 UTC, closed without merging