Added scalafmt configuration file to force common formatting style.
anitvam/pps-bunny pull request #58
Opened 2021-09-22 13:48 UTC by aslucc

Closes #45.

2021-09-22 13:57 UTC, alessiarocco98 approved these changes

2021-09-22 15:27 UTC, anitvam approved these changes

2021-09-23 08:22 UTC, anitvam requested changes
Ho notato che la configurazione di scala fmt non segue le regole di stile che abbiamo adottato fin'ora: non permette di fare la notazione infissa e spezza tutte le funzioni passate come parametro. Ti lascio la proposta per il nuovo file di configurazione nei commenti, l'ho testata sul mio pc.

2021-09-23 08:37 UTC, anitvam commented on .scalafmt.conf
> +
```suggestion
version = 3.0.0
maxColumn = 120

includeCurlyBraceInSelectChains = false

# Indent
indent.main = 2

# Alignment
align.openParenCallSite = false
align.openParenDefnSite = false
align.preset = some

# Newlines
newlines.penalizeSingleSelectMultiArgList = false
newlines.topLevelStatementBlankLines = [
  { blanks = { before = 1, after = 1 } }
]
newlines.beforeMultiline = fold
newlines.implicitParamListModifierPrefer = before
newlines.avoidInResultType = true
danglingParentheses.defnSite = true
danglingParentheses.callSite = true

# Docstring
docstrings.style = Asterisk
docstrings.wrap = yes

# Project
project.git = true
project.excludeFilters = ["target/", ".idea/", ".bsp/"]

# Rewrite
rewrite.rules = [SortModifiers, PreferCurlyFors, Imports]
rewrite.imports.sort = scalastyle
rewrite.sortModifiers.order = [
  "implicit", "private", "sealed", "abstract", "override", "final", "protected", "lazy"
]

rewriteTokens = {
  "⇒": "=>"
  "→": "->"
  "←": "<-"
}

# Space
spaces.inImportCurlyBraces = true

# Other
optIn.breakChainOnFirstMethodDot = false
importSelectors = binPack
```

2021-09-23 08:38 UTC, anitvam commented on .scalafmt.conf
> +
però per avere queste modifiche bisogna ripassare tutti i file, quindi ti consiglio di tornare indietro nei commit ....

2021-09-23 08:40 UTC, anitvam commented
è possibile configurare intellij per avere le modifiche di fmt in automatico al salvataggio del file in questo modo: 
![image](https://user-images.githubusercontent.com/39519366/134477818-e699fb34-7d53-4eb2-974d-6418a5b32978.png)

2021-09-23 10:33 UTC, closed without merging