Feature/ar gui clock
anitvam/pps-bunny pull request #78
Opened 2021-10-04 08:46 UTC by alessiarocco98

- Add stylesheet of the clock via css
- Create the clock via ScalaFx components trhough ClockController
- Add method to ScalaFXView to manage clock working

2021-10-04 08:53 UTC, aslucc commented on src/main/scala/engine/Simulation.scala
> +    ScalaFXView.updateClock("Wolves")
Qui al posto di passare la stringa, si potrebbe usare l'enumerazione delle varie fasi (credo che la Marta l'abbia fatta da qualche parte), associando inoltre ad ogni fase un `prettyName` da usare del testo della Label

2021-10-04 08:55 UTC, aslucc commented on src/main/scala/view/scalaFX/ScalaFXView.scala
> +object ScalaFxViewConstants {
Questo oggetto l'abbiamo messo in un file separato, perciò va tolto da ScalaFXView

2021-10-04 09:03 UTC, aslucc requested changes
![Schermata 2021-10-04 alle 11 01 18](https://user-images.githubusercontent.com/65169380/135823418-13cd463e-5b4d-41c9-b581-c9535afa5859.png)
Io vedo il clock in questo modo:
+ lo sposterei un po' più in alto in modo a essere allineato con i bottoni a destra
+ metterei la label sotto il clock invece che al suo interno in modo che non si sovrapponga con le "lancette" o gli orari

2021-10-04 09:05 UTC, aslucc commented on src/main/scala/view/scalaFX/FXControllers/ClockController.scala
> +      val tick = Line(0, -23, 0, -33)
Magic numbers

2021-10-05 10:15 UTC, aslucc reviewed
Ho notato altri due piccoli difetti:
+ C'è una strana ombra grigia nella zona in basso a destra dell'orologio.
+ Nel momento della "Generation" l'orologio si trova già a ore 3, non forse dovrebbe essere a ore 12 o a metà fra ore 12 e ore 3? Temperature per come è fatto ora si trova a ore "12" e secondo me sembra che venga fatto all'inizio della nuova generazione, invece è l'ultima cosa facciamo nella generazione precedente. Quest'ultima cosa è stata modificata ora perchè nello screen precedente si può vedere che New Generation è a ore 12.

2021-10-05 10:46 UTC, anitvam reviewed
Ho qualche problema: 
- i lupi non mi spariscono mai 
- il clock quando inizia la generazione deve essere alle ore 12 non alle 3
- metteresti la scritta sopra l'orologio? così si legge meglio

2021-10-05 10:53 UTC, alessiarocco98 commented
> Ho notato altri due piccoli difetti:
> 
> * C'è una strana ombra grigia nella zona in basso a destra dell'orologio.
> * Nel momento della "Generation" l'orologio si trova già a ore 3, non forse dovrebbe essere a ore 12 o a metà fra ore 12 e ore 3? Temperature per come è fatto ora si trova a ore "12" e secondo me sembra che venga fatto all'inizio della nuova generazione, invece è l'ultima cosa facciamo nella generazione precedente. Quest'ultima cosa è stata modificata ora perchè nello screen precedente si può vedere che New Generation è a ore 12.

- l'ombra era voluta per far sembrare l'orologio sopra ai coniglietti ma se da fastidio la tolgo.
- Correggo subito questa cosa perchè il bug credo sia dovuto al fatto che all'inizio la riproduzione non c'è e non viene richiamato lo spostamento delle lancette, quindi magari l'orologio all'inizio parte con le lancette spostate di 90° indietro in modo tale che appena il gioco parta imposti alle 12 la nuova generazione

2021-10-05 10:55 UTC, alessiarocco98 commented
> Ho qualche problema:
> 
> * i lupi non mi spariscono mai
> * il clock quando inizia la generazione deve essere alle ore 12 non alle 3
> * metteresti la scritta sopra l'orologio? così si legge meglio

- i lupi ora non spariscono perché la correzione è nel branch feature/ar-gui-factors-try che non è ancora mergiato su develop.
- ok metto la scritta sopra, il colore della scritta sempre nero o preferite un altro colore?

2021-10-05 13:01 UTC, aslucc approved these changes

2021-10-06 14:41 UTC, martaSpadoni commented on src/main/scala/view/scalaFX/FXControllers/BaseAppController.scala
> +
Sinceramente a me non piace molto che venga usato tutte le volte il nome dell'object che racchiude le costanti delle fasi, che tra l'altro non trovo neanche molto utile, se ne poteva al massimo creare uno solo per tutte. Comunque ho intenzione di rifattorizzare questa parte con una Enum quindi per ora puoi togliere i nomi degli object

2021-10-06 14:43 UTC, martaSpadoni commented on src/main/scala/view/scalaFX/FXControllers/ClockController.scala
> +    labelClock.layoutYProperty().bind(clock.layoutYProperty().subtract(20))
se non erro esiste un dsl per fare il bind delle property, qualcosa tipo `<<`

2021-10-06 14:45 UTC, martaSpadoni commented on src/main/scala/view/scalaFX/FXControllers/ClockController.scala
> +      val tick = Line(0, -23, 0, -33)
Questa conversazione è marcata come risolta ma io vedo ancora i magic number...

2021-10-06 15:21 UTC, aslucc commented on src/main/scala/view/scalaFX/FXControllers/ClockController.scala
> +    labelClock.layoutYProperty().bind(clock.layoutYProperty().subtract(20))
Dovrebbe essere <== (https://www.scalafx.org/docs/properties/)

2021-10-06 17:36 UTC, anitvam reviewed
Il file ClockController non è un controller. È un componente della View che non ha nulla a che fare con i controllers in quanto non possiede un fxml allegato. Rinominalo e mettilo in components per essere coerenti.

2021-10-07 09:36 UTC, alessiarocco98 commented on src/main/scala/view/scalaFX/FXControllers/BaseAppController.scala
> +
Ti lascio qui questa semplice enum di come avrei fatto io:
object GenerationConstants extends Enumeration {
  val REPRODUCTION_PHASE: String = "Reproduction"
  val WOLVES_PHASE: String = "Wolves"
  val FOOD_PHASE: String = "Food"
  val HIGH_TEMPERATURE_PHASE: String = "Temperature"
}

2021-10-07 17:26 UTC, martaSpadoni commented on src/main/scala/model/world/Generation.scala
> +  val HIGH_TEMPERATURE = GenerationPhaseConstantsVal("Temperature")
No questa enum è completamente inutile così avevo già detto che ci avrei pensato io rifattorizzare questa parte di codice.

2021-10-07 17:31 UTC, martaSpadoni commented on src/main/scala/view/scalaFX/FXControllers/BaseAppController.scala
> +
qui è molto brutto che venga richiamato 4 volte updateClock solo per differenziare le fasi, rifattorizza in modo tale che updateClock prenda in input la generationPhase e poi sposti il check su quale sia la fase

2021-10-08 07:27 UTC, anitvam approved these changes

2021-10-08 07:27 UTC, anitvam approved these changes
Sistema le cose della marta e per me è a posto

2021-10-08 09:04 UTC, martaSpadoni commented on src/main/scala/view/scalaFX/FXControllers/BaseAppController.scala
> +  private def updateClock(generationPhase: GenerationPhase): Unit = clockController.updateClock(generationPhase)
non ha senso richiamare questo metodo, fai direttamente in updateView `clockController.updateClock(generationPhase)`

2021-10-08 09:10 UTC, alessiarocco98 commented on src/main/scala/view/scalaFX/components/Clock.scala
> +  def updateClock(generationPhase: GenerationPhase, angle: Double = angle): Unit
mi serve solo per sfruttare lo stesso metodo nell'inizializzazione quando devo ruotare la lancetta indietro prima che parta la simulazione. Altrimenti lascio come era prima con la ripetizione dell'aggiunta di una `new Rotate()` in `trasformations`

2021-10-08 11:27 UTC, merged